import json
import os
import platform
from pathlib import Path
from typing import Any, Literal, Optional, Union, get_args

from pydantic import (
    BaseModel,
    Field,
    HttpUrl,
    ValidationError,
    field_validator,
    model_validator,
)


class ConfluenceConfig(BaseModel):
    url: HttpUrl
    username: str
    api_token: str
    timeout: int = 10


class SearchConfig(BaseModel):
    default_limit: int = 20
    max_limit: int = 100
    default_expand: list[str] = ["body.view", "space"]


class EmbeddingConfig(BaseModel):
    provider: Literal["sentence-transformers", "litellm", "none"] = Field(
        default="none",
        description="The type of embedding provider to use ('sentence-transformers', 'litellm', or 'none').",
    )
    model_name: Optional[str] = Field(
        default=None,
        description="Name or path of the embedding model. "
        "Examples: 'all-MiniLM-L6-v2' (for sentence-transformers), "
        "'openai/text-embedding-ada-002', 'ollama/nomic-embed-text' (for litellm).",
    )
    dimension: Optional[int] = Field(
        default=None,
        description="Expected dimension of the embeddings generated by the model. "
        "Required if provider is not 'none'.",
    )
    litellm_api_key: Optional[str] = Field(
        default=None,
        description="API key for the LiteLLM provider (e.g., OpenAI, Cohere API key). "
        "Store securely, preferably via environment variable.",
        exclude=True,
    )
    litellm_api_base: Optional[HttpUrl] = Field(
        default=None,
        description="API base URL for the LiteLLM provider. "
        "Required for providers like Azure OpenAI or self-hosted models (e.g., Ollama).",
    )
    device: Optional[Literal["cpu", "cuda"]] = Field(
        default=None,
        description="Device to use for sentence-transformers ('cpu' or 'cuda'). "
        "If None, it will auto-detect. Ignored for 'litellm' provider.",
    )

    @model_validator(mode="after")
    def check_conditional_requirements(self) -> "EmbeddingConfig":
        if self.provider != "none":
            if not self.model_name:
                raise ValueError(
                    "EMBEDDING_MODEL_NAME must be set if EMBEDDING_PROVIDER is not 'none'."
                )
            if self.dimension is None:
                raise ValueError(
                    "EMBEDDING_DIMENSION must be set if EMBEDDING_PROVIDER is not 'none'."
                )

        if self.provider == "litellm":
            if self.model_name and self.model_name.startswith("ollama/"):
                if not self.litellm_api_base:
                    raise ValueError(
                        "LITELLM_API_BASE must be set when using an 'ollama/' model with the 'litellm' provider."
                    )

        if self.provider == "sentence-transformers":
            if self.litellm_api_key or self.litellm_api_base:
                print(
                    "Warning: LITELLM_API_KEY and LITELLM_API_BASE are ignored when EMBEDDING_PROVIDER is 'sentence-transformers'."
                )
            elif self.provider == "litellm":
                if self.device:
                    print(
                        "Warning: EMBEDDING_DEVICE is ignored when EMBEDDING_PROVIDER is 'litellm'."
                    )

        return self


VectorDBType = Literal["chroma", "qdrant", "none"]


class IndexingConfig(BaseModel):
    include_spaces: Optional[list[str]] = Field(
        default=None,
        description="List of space keys to explicitly include in indexing. If set, only these spaces are considered.",
    )
    exclude_spaces: Optional[list[str]] = Field(
        default=None,
        description="List of space keys to explicitly exclude from indexing. Applied after include_spaces.",
    )
    html_parser: Literal["markitdown", "unstructured"] = Field(
        default="markitdown",
        description="Parser to use for extracting text from Confluence page HTML ('markitdown' or 'unstructured').",
    )
    include_attachments: bool = Field(
        default=False,
        description="Enable or disable indexing of attachments.",
    )
    max_attachment_size_mb: int = Field(
        default=10,
        ge=0,
        description="Maximum size in MB for an attachment to be processed.",
    )
    allowed_attachment_extensions: Optional[list[str]] = Field(
        default=["pdf", "docx", "pptx", "txt", "md"],
        description="List of file extensions to process. If None or empty, attempts all supported types. Case-insensitive.",
    )
    attachment_parser: Literal["markitdown", "unstructured"] = Field(
        default="markitdown",
        description="Parser to use for extracting text from attachments ('markitdown' or 'unstructured').",
    )

    @field_validator("html_parser", "attachment_parser")
    @classmethod
    def check_parser_name(cls, v: str) -> str:
        """Validate that the parser name is one of the known types."""
        valid_parsers = {"markitdown", "unstructured"}
        if v.lower() not in valid_parsers:
            raise ValueError(
                f"Invalid parser name '{v}'. Must be one of: {', '.join(valid_parsers)}"
            )
        return v.lower()  # Return the lowercased version

    @model_validator(mode="before")
    @classmethod
    def normalize_extensions(cls, values: dict[str, Any]) -> dict[str, Any]:
        extensions = values.get("allowed_attachment_extensions")
        if isinstance(extensions, list):
            values["allowed_attachment_extensions"] = [
                ext.lower().lstrip(".") for ext in extensions if isinstance(ext, str)
            ]
        return values


def get_user_config_path() -> Path:
    return Path.home() / ".confluence_gateway_config.json"


def _load_config_from_file(path: Path) -> dict[str, Any]:
    config_data = {}
    if path.exists() and path.is_file():
        try:
            with open(path, encoding="utf-8") as f:
                config_data = json.load(f)
            if not isinstance(config_data, dict):
                print(
                    f"Warning: Config file at {path} does not contain a valid JSON object. Ignoring."
                )
                return {}
            print(f"Info: Loaded configuration from {path}")
        except json.JSONDecodeError:
            print(
                f"Warning: Could not parse JSON from config file at {path}. Ignoring."
            )
            return {}
        except Exception as e:
            print(f"Warning: Error reading config file at {path}: {e}. Ignoring.")
            return {}
    return config_data


class VectorDBConfig(BaseModel):
    type: VectorDBType = Field(
        default="none", description="The type of vector database to use."
    )
    collection_name: str = Field(
        default="confluence_embeddings",
        description="Name of the collection/table in the vector database.",
    )
    embedding_dimension: Optional[int] = Field(
        default=None,
        description="Dimension of the text embeddings. Required if type is not 'none'.",
    )
    chunk_size: int = Field(
        default=512,
        description="Target size for text chunks during indexing.",
    )
    chunk_overlap: int = Field(
        default=50,
        description="Overlap between consecutive text chunks during indexing.",
    )

    chroma_persist_path: Optional[str] = Field(
        default=None,
        description="Path for ChromaDB persistent storage. Client mode takes precedence if host/port are set.",
    )
    chroma_host: Optional[str] = Field(
        default=None, description="Hostname for ChromaDB client/server mode."
    )
    chroma_port: Optional[int] = Field(
        default=None, description="Port for ChromaDB client/server mode."
    )

    qdrant_url: Optional[Union[HttpUrl, Literal[":memory:"]]] = Field(
        default=None,
        description="URL for the Qdrant instance. Required if type is 'qdrant'. Can be ':memory:' for in-memory testing.",
    )
    qdrant_api_key: Optional[str] = Field(
        default=None, description="API key for Qdrant authentication."
    )
    qdrant_grpc_port: int = Field(
        default=6334, description="Port for Qdrant gRPC connections."
    )
    qdrant_prefer_grpc: bool = Field(
        default=False, description="Prefer gRPC over HTTP for Qdrant."
    )

    @model_validator(mode="after")
    def check_conditional_requirements(self) -> "VectorDBConfig":
        if self.type != "none":
            if self.embedding_dimension is None:
                raise ValueError(
                    "VECTOR_DB_EMBEDDING_DIMENSION must be set if VECTOR_DB_TYPE is not 'none'."
                )

        if self.type == "qdrant":
            if self.qdrant_url is None:
                raise ValueError(
                    "QDRANT_URL must be set if VECTOR_DB_TYPE is 'qdrant'."
                )

        return self


def _load_raw_env_vars(prefix: str, case_sensitive: bool = False) -> dict[str, Any]:
    """Load environment variables with given prefix into a dictionary."""
    env_vars = {}

    # Windows environment variables are case-insensitive
    is_windows = platform.system().lower() == "windows"
    effective_case_sensitive = case_sensitive and not is_windows

    prefix_upper = prefix.upper()
    prefix_len = len(prefix)

    for key, value in os.environ.items():
        key_to_check = key if effective_case_sensitive else key.upper()
        prefix_to_check = prefix if effective_case_sensitive else prefix_upper

        if key_to_check.startswith(prefix_to_check):
            config_key = (
                key[prefix_len:].lower()
                if not effective_case_sensitive
                else key[prefix_len:]
            )
            env_vars[config_key] = value

    return env_vars


def _try_convert_to_int(config: dict[str, Any], key: str, error_message: str) -> None:
    """Try to convert a string value to an integer in the config dict."""
    if key in config and isinstance(config[key], str):
        try:
            config[key] = int(config[key])
        except ValueError:
            print(error_message)
            del config[key]


def _load_raw_search_env() -> dict[str, Any]:
    """Load search configuration from environment variables."""
    validations = {
        "default_limit": int,
        "max_limit": int,
        "default_expand": "comma_list",
    }

    return _load_env_with_validation("SEARCH_", validations)


def _load_raw_confluence_env() -> dict[str, Any]:
    confluence_env = _load_raw_env_vars("CONFLUENCE_")

    if "timeout" in confluence_env and isinstance(confluence_env["timeout"], str):
        try:
            confluence_env["timeout"] = int(confluence_env["timeout"])
        except ValueError:
            print("Warning: Invalid CONFLUENCE_TIMEOUT value, using default.")
            del confluence_env["timeout"]

    return confluence_env


def _load_raw_vector_db_env() -> dict[str, Any]:
    """Load vector database configuration from environment variables."""
    # Base vector DB config
    validations = {
        "type": get_args(VectorDBType),
        "embedding_dimension": int,
        "chunk_size": int,
        "chunk_overlap": int,
    }

    raw_config = _load_env_with_validation("VECTOR_DB_", validations)

    # Chroma-specific config
    for env_var, config_key in [
        ("CHROMA_PERSIST_PATH", "chroma_persist_path"),
        ("CHROMA_HOST", "chroma_host"),
    ]:
        if value := os.getenv(env_var):
            raw_config[config_key] = value

    if port_str := os.getenv("CHROMA_PORT"):
        try:
            raw_config["chroma_port"] = int(port_str)
        except ValueError:
            raw_config["chroma_port"] = port_str

    # Qdrant-specific config
    for env_var, config_key in [
        ("QDRANT_URL", "qdrant_url"),
        ("QDRANT_API_KEY", "qdrant_api_key"),
    ]:
        if value := os.getenv(env_var):
            raw_config[config_key] = value

    if grpc_port_str := os.getenv("QDRANT_GRPC_PORT"):
        try:
            raw_config["qdrant_grpc_port"] = int(grpc_port_str)
        except ValueError:
            raw_config["qdrant_grpc_port"] = grpc_port_str

    if prefer_grpc_str := os.getenv("QDRANT_PREFER_GRPC"):
        raw_config["qdrant_prefer_grpc"] = prefer_grpc_str.lower() in [
            "true",
            "1",
            "t",
            "yes",
            "y",
        ]

    return raw_config


def _load_env_with_validation(
    prefix: str, validations: dict[str, Any] = None
) -> dict[str, Any]:
    """Load environment variables with given prefix, applying optional type conversions and validations."""
    raw_config = _load_raw_env_vars(prefix)

    if not validations:
        return raw_config

    for key, validator in validations.items():
        if key not in raw_config:
            continue

        value = raw_config[key]

        # Handle type conversions
        if isinstance(validator, type):
            try:
                if validator is int:
                    raw_config[key] = int(value)
                elif validator is bool and isinstance(value, str):
                    raw_config[key] = value.lower() in ["true", "1", "t", "yes", "y"]
                # Add more type conversions as needed
            except ValueError:
                # Keep the original value, let validation models handle errors
                pass

        # Handle enum validation
        elif isinstance(validator, list):
            if isinstance(value, str) and value.lower() not in [
                str(v).lower() for v in validator
            ]:
                print(
                    f"Warning: Invalid {prefix}{key} '{value}' in environment. Using default."
                )
            elif isinstance(value, str):
                raw_config[key] = value.lower()

        # Handle comma-separated lists
        elif validator == "comma_list" and isinstance(value, str):
            raw_config[key] = [s.strip() for s in value.split(",") if s.strip()]

        # Add more validation types as needed

    return raw_config


def _load_raw_embedding_env() -> dict[str, Any]:
    """Load embedding configuration from environment variables."""
    validations = {
        "provider": get_args(Literal["sentence-transformers", "litellm", "none"]),
        "dimension": int,
        "device": get_args(Literal["cpu", "cuda"]),
    }

    raw_config = _load_env_with_validation("EMBEDDING_", validations)

    # Add specific LITELLM variables
    for env_var, config_key in [
        ("LITELLM_API_KEY", "litellm_api_key"),
        ("LITELLM_API_BASE", "litellm_api_base"),
    ]:
        if value := os.getenv(env_var):
            raw_config[config_key] = value

    return raw_config


def _load_raw_indexing_env() -> dict[str, Any]:
    """Load indexing configuration from environment variables."""
    validations = {
        "include_spaces": "comma_list",
        "exclude_spaces": "comma_list",
        "html_parser": get_args(Literal["markitdown", "unstructured"]),
        "include_attachments": bool,
        "max_attachment_size_mb": int,
        "allowed_attachment_extensions": "comma_list",
        "attachment_parser": get_args(Literal["markitdown", "unstructured"]),
    }

    raw_config = _load_env_with_validation("INDEXING_", validations)

    # Process extension list to ensure proper format
    if "allowed_attachment_extensions" in raw_config and isinstance(
        raw_config["allowed_attachment_extensions"], list
    ):
        raw_config["allowed_attachment_extensions"] = [
            ext.lower().lstrip(".")
            for ext in raw_config["allowed_attachment_extensions"]
        ]

    return raw_config


def load_configurations() -> tuple[
    Optional[ConfluenceConfig],
    SearchConfig,
    Optional[VectorDBConfig],
    Optional[EmbeddingConfig],
    IndexingConfig,
]:
    user_config_path = get_user_config_path()
    file_config = _load_config_from_file(user_config_path)

    env_confluence_raw = _load_raw_confluence_env()
    env_search_raw = _load_raw_search_env()
    env_vector_db_raw = _load_raw_vector_db_env()
    env_embedding_raw = _load_raw_embedding_env()
    env_indexing_raw = _load_raw_indexing_env()

    file_confluence = file_config.get("confluence", {})
    file_search = file_config.get("search", {})
    file_vector_db = file_config.get("vector_db", {})
    file_embedding = file_config.get("embedding", {})
    file_indexing = file_config.get("indexing", {})

    final_confluence_config = env_confluence_raw.copy()
    final_confluence_config.update(file_confluence)

    final_search_config = env_search_raw.copy()
    final_search_config.update(file_search)

    final_vector_db_config = env_vector_db_raw.copy()
    final_vector_db_config.update(file_vector_db)

    final_embedding_config = env_embedding_raw.copy()
    final_embedding_config.update(file_embedding)

    final_indexing_config = env_indexing_raw.copy()
    final_indexing_config.update(file_indexing)

    loaded_confluence_config: Optional[ConfluenceConfig] = None
    required_confluence_fields = ["url", "username", "api_token"]
    if all(field in final_confluence_config for field in required_confluence_fields):
        try:
            loaded_confluence_config = ConfluenceConfig(**final_confluence_config)
        except ValidationError as e:
            print(f"Error: Invalid Confluence configuration: {e}")
            print("Warning: Confluence client cannot be initialized.")
    else:
        print(
            "Info: Essential Confluence configuration (url, username, api_token) not found. Confluence client disabled."
        )

    try:
        loaded_search_config = SearchConfig(**final_search_config)
    except ValidationError as e:
        print(f"Error: Invalid Search configuration: {e}. Using defaults.")
        loaded_search_config = SearchConfig()

    loaded_embedding_config: Optional[EmbeddingConfig] = None
    if final_embedding_config:
        if "provider" not in final_embedding_config:
            final_embedding_config["provider"] = "none"
            print("Info: Embedding provider type missing, defaulting to 'none'.")

        try:
            filtered_emb_config = {
                k: v for k, v in final_embedding_config.items() if v is not None
            }
            if (
                "provider" not in filtered_emb_config
                and "provider" in final_embedding_config
            ):
                filtered_emb_config["provider"] = final_embedding_config["provider"]

            config_instance = EmbeddingConfig(**filtered_emb_config)
            if config_instance.provider != "none":
                loaded_embedding_config = config_instance
                print()
            else:
                print("Info: Embedding provider is disabled (provider='none').")

        except (ValidationError, ValueError) as e:
            print(f"Error: Invalid Embedding configuration: {e}")
            print()
    else:
        print("Info: No Embedding configuration found. Embedding features disabled.")

    if loaded_embedding_config and loaded_embedding_config.dimension is not None:
        vdb_type = final_vector_db_config.get("type", "none")
        if vdb_type != "none" and "embedding_dimension" not in final_vector_db_config:
            final_vector_db_config["embedding_dimension"] = (
                loaded_embedding_config.dimension
            )
            print(
                f"Info: Setting VectorDB embedding_dimension from EmbeddingConfig: {loaded_embedding_config.dimension}"
            )
        elif (
            vdb_type != "none"
            and "embedding_dimension"
            in final_vector_db_config  # Check key exists before comparing
            and final_vector_db_config.get("embedding_dimension")
            != loaded_embedding_config.dimension
        ):
            print(
                f"Warning: VECTOR_DB_EMBEDDING_DIMENSION ({final_vector_db_config.get('embedding_dimension')}) "
                f"differs from EMBEDDING_DIMENSION ({loaded_embedding_config.dimension}). Using the VectorDB specific value."
            )
    loaded_vector_db_config: Optional[VectorDBConfig] = None
    if final_vector_db_config:
        if "type" not in final_vector_db_config:
            final_vector_db_config["type"] = "none"
            print("Info: Vector DB type missing, defaulting to 'none'.")

        try:
            filtered_vdb_config = {
                k: v for k, v in final_vector_db_config.items() if v is not None
            }
            if "type" not in filtered_vdb_config and "type" in final_vector_db_config:
                filtered_vdb_config["type"] = final_vector_db_config["type"]

            config_instance = VectorDBConfig(**filtered_vdb_config)

            if config_instance.type != "none":
                loaded_vector_db_config = config_instance
                print()
            else:
                print("Info: Vector database integration is disabled (type='none').")

        except (ValidationError, ValueError) as e:
            print(f"Error: Invalid Vector DB configuration: {e}")
            print()
    else:
        print("Info: No Vector DB configuration found. Vector DB features disabled.")

    try:
        loaded_indexing_config = IndexingConfig(**final_indexing_config)
    except ValidationError as e:
        print(f"Error: Invalid Indexing configuration: {e}. Using defaults.")
        loaded_indexing_config = IndexingConfig()

    return (
        loaded_confluence_config,
        loaded_search_config,
        loaded_vector_db_config,
        loaded_embedding_config,
        loaded_indexing_config,
    )


(
    confluence_config,
    search_config,
    vector_db_config,
    embedding_config,
    indexing_config,
) = load_configurations()
