name: CI

on:
  push:
    branches: [ master, feat/* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: "pyproject.toml"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync
          uv pip install -e ".[dev]"

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

      - name: Run tests
        if: ${{ success() }}
        run: |
          uv run pytest tests/ -v
